# Generated by Django 4.0 on 2021-12-16 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_servicos_servico_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='nome',
            new_name='titulo',
        ),
    ]
