# Generated by Django 4.0 on 2021-12-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_nome_servico_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='image',
            field=models.ImageField(height_field=150, upload_to='', verbose_name='FotoDoProduto', width_field=150),
        ),
        migrations.AlterField(
            model_name='servico',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.IntegerField(verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='enderco',
            field=models.CharField(max_length=30, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idade',
            field=models.IntegerField(verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nomeCompleto',
            field=models.CharField(max_length=50, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rg',
            field=models.IntegerField(verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=10, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.IntegerField(verbose_name='Celular'),
        ),
    ]
